version: "3.9"
services:
  php:
    platform: linux/amd64
    image: yiisoftware/yii2-php:8.2-fpm-nginx
    volumes:
      - ..:/var/www:delegated
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:delegated
      - ./php.ini:/usr/local/etc/php/conf.d/base.ini:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    environment:
      - ENVIRONMENT=development
      - PHP_ENABLE_XDEBUG=1
    ports:
      - 75:80
    working_dir: /var/www
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:${MYSQL_VERSION:-8.0.22}
    restart: always
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root # development purposes only
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
#      - ./dump.sql:/dump.sql
      - mysql:/var/lib/mysql
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    networks:
      - default
volumes:
  mysql: